---
- name: Collect System Logs
  hosts: ubuntu_hosts
  gather_facts: true
  tasks:
    - name: Create directory with target host's IP
      local_action:
        module: file
        path: "./{{ inventory_hostname }}"
        state: directory

    - name: Copy syslog from target host to the created directory
      become: yes
      copy:
        src: /var/log/syslog
        dest: "./{{ inventory_hostname }}/syslog_from_{{ inventory_hostname }}"
      delegate_to: localhost

- name: Execute Python script to convert syslog to CSV
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Run Python script
      command: python3 syslog_to_csv.py
